I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 90, in script
    $ start_time = renpy.get_ticks_milliseconds()
  File "game/script.rpy", line 90, in <module>
    $ start_time = renpy.get_ticks_milliseconds()
AttributeError: module 'renpy.exports' has no attribute 'get_ticks_milliseconds'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 90, in script
    $ start_time = renpy.get_ticks_milliseconds()
  File "C:\Program Files (x86)\renpy-8.2.1-sdk\renpy\ast.py", line 823, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Program Files (x86)\renpy-8.2.1-sdk\renpy\python.py", line 1178, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 90, in <module>
    $ start_time = renpy.get_ticks_milliseconds()
AttributeError: module 'renpy.exports' has no attribute 'get_ticks_milliseconds'

Windows-10-10.0.22631 AMD64
Ren'Py 8.2.2.24041101+nightly
Crow_Crowd 1.0
Sat May  4 15:05:40 2024
